### ISSUE TITLE
Review: ProfileCard.jsx & [ProfileWidget.jsx

### ISSUE THREAD

**Issue by kaleinah** [hh-t1/hacc-hui-revamped#62]
# Files to review
[ProfileCard.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/ProfileCard.jsx)
[ProfileWidget.jsx](https://github.com/hh-t1/hacc-hui-revamped/blob/master/app/imports/ui/components/participant/ProfileWidget.jsx)

# Checklists
[Architecture](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/architecture-checklist.md)
[Design](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/design-checklist.md)
[JS](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/js-checklist.md)
[React](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/react-checklist.md)
[Testing](https://github.com/bang-software/HACC-Hui-414f23/blob/main/checklists/testing-checklist.md)

# Due date
September 26, 2023

**Comment by winstonco** [comment]
## ProfileCard.jsx
### Architecture
Looks good
### Design
Looks good
### JavaScript and ESLint
[ES-01]: Prettier complaint: 1 tag per line, some lines too long
### React
[RE-09]: Use a function component
Use bootstrap instead of sem ui
### Testing
[TA-01][TA-02]: No tests written, but tests are unnecessary

## ProfileWidget.jsx
### Architecture
[AR-01]: I know it’s according to the convention of the rest of the app, but I don’t like having “Widget” in the name
### Design
Looks good
### JavaScript and ESLint
[JS-05]: Replace lodash functions with native array functions
[ES-01]: Prettier complaint: 1 tag per line, some lines too long
### React
[RE-09]: Should be a function component
[RE-09]: useTracker instead of withTracker
Use bootstrap instead of sem ui
### Testing
[TA-01][TA-02]: No tests written, but tests are unnecessary

**Comment by km584** [comment]
### **ProfileCard.jsx**
RE-09: L7,8 Should be remove extends and render from class
RE-10: avoid card

### **ProfileWidget.jsx**
DE-05: L33 remove unused comment
JS-05: L22, 66 avoid loadash
RE-09: L18, 31 Should remove extends and render from class
RE-10: avoid widget

**Comment by ntomchak** [comment]
ProfileCard.jsx
RE-09: make functional component
RE-10: remove card from name

ProfileWidget.jsx
DE-05: L32
J2-05: L7, L22
RE-09: make functional component
RE-10: remove widget from name

**Comment by rhlai** [comment]
ProfileWidget.jsx
JS-04: L18
JS-05: L22
RE-09: L18
RE-10

ProfileCard.jsx
JS-04: L7
RE-09: L7

**Comment by winstonco** [comment]
Outcome of review:
ProfileCard.jsx
- make function component
- convert to bootstrap
ProfileWidget.jsx
- make function component
- fix name
- remove lodash
- use useTracker instead of withTracker
- convert to bootstrap

**Comment by Rubegen** [comment]
ProfileCard.jsx
JS-04   L18
JS-05   L22
RE-09
RE-10


ProfileWidget.jsx
RE-09
RE-10
